services:
  - type: web
    name: phq-bookmark-manager
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist/phq-bookmark-manager-test
    envVars:
      - key: NODE_VERSION
        value: 22.0.0 